---
title: "LLM usage log"
---

The LLM tool (Claude) was used in the following way for the tasks below


## Code: 
Claude was mostly used to generate the aesthetic code for the website such as the color scheme and font choices.It was used to generate the index.html skeleton for my website. Specifically, it provided the html code and structure for the typing effect for my titles throughout the website. The CSS styling and Javascript for the scrolling effect on the website was also generated by Claude. I also needed guidance for the carousel of image at the start of the project but that was just generating the time sequence. It was used to aid in generating the dropdown menus for the calculator section of the website. I also used it to generate the code for the calculator itself, which is an iframe embedded in the website. I then edited the code generated by Claude to fit my needs and to ensure it was error free

## My Role:

I maintained complete creative control throughout the narrative. I came up with all of the hypotheses and narrative using prior economic knowledge from IB HL Economics in high school. I designed the plot development framework.  Once I put in my prompt into the LLM for the website's aesthetic, I reviewed the code generated by the LLM carefully to ensure it met my analytical goals and that i understood it.



